# Generated by Django 4.0.3 on 2022-03-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=64)),
            ],
        ),
    ]
