# Generated by Django 4.0.3 on 2022-03-19 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogs',
            new_name='Blog',
        ),
    ]
