# Generated by Django 4.0.3 on 2022-03-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.TextField()),
                ('competion', models.TextField()),
                ('officialinfo', models.TextField()),
                ('build', models.TextField()),
                ('sample1', models.TextField()),
                ('sample2', models.TextField()),
                ('sample3', models.TextField()),
                ('conclusion', models.TextField()),
            ],
        ),
    ]
