# Generated by Django 4.0.3 on 2022-03-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Years', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='years',
            old_name='sample1',
            new_name='caption1',
        ),
        migrations.RenameField(
            model_name='years',
            old_name='sample2',
            new_name='caption2',
        ),
        migrations.RenameField(
            model_name='years',
            old_name='sample3',
            new_name='caption3',
        ),
        migrations.AddField(
            model_name='years',
            name='caption4',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='years',
            name='image2',
            field=models.FileField(null=True, upload_to='static/img/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='years',
            name='video1',
            field=models.FileField(null=True, upload_to='static/videos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='years',
            name='video2',
            field=models.FileField(null=True, upload_to='static/videos/', verbose_name=''),
        ),
    ]
