# Generated by Django 4.0.3 on 2022-03-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Years', '0002_rename_sample1_years_caption1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='years',
            name='image1',
            field=models.FileField(null=True, upload_to='static/img/', verbose_name=''),
        ),
    ]
