# Generated by Django 4.0.3 on 2022-03-24 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Years', '0003_years_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='years',
            name='competition',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='years',
            name='season',
            field=models.CharField(max_length=64),
        ),
    ]
