# Generated by Django 4.0.3 on 2022-03-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Years', '0004_years_competition_alter_years_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='years',
            name='build',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='years',
            name='caption1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='years',
            name='caption2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='years',
            name='caption3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='years',
            name='caption4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='years',
            name='competion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='years',
            name='competition',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='years',
            name='conclusion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='years',
            name='officialinfo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='years',
            name='season',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='years',
            name='video1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='years',
            name='video2',
            field=models.TextField(null=True),
        ),
    ]
