# Generated by Django 4.0.3 on 2022-03-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_History', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
